#####################################################################################
#
#		James Matthews, University of Southampton
#					6 Feb 2014
#
# This is the travis yml file which controls the test builds 
# for Python, the radiative transfer code hosted at https://github.com/agnwinds/python
#
# Procedure:
#		- travis automatically clones the main dev branch of the repository
#   	- we clone the rest of the directory structure into a folder called structure
# 		- note this is different from normal directory layout, but facilitates the build
#		- Cfitsio and gsl are built
#   	- we then cd into the main build directory and do make test_tr. 
#   
#####################################################################################

language: c

compiler:
    - gcc

# only want to run this test when we commit to dev
branches:
  only:
      dev
      structure
script:
    # clone the structure branch into a sub directory
    - export PYTHON=$PWD
    - make CMAKE=gcc install

