language: c
compiler:
    - gcc

env:
    - PYTHON = $TRAVIS_BUILD_DIR

branches:
  only:
    - structure


install:
    # First make cfitsio library
    - echo $PYTHON
    - export PYTHON=$TRAVIS_BUILD_DIR
    - cd software/cfitsio3040
    -  ./configure 
    - make
    - mv libcfitsio.a ../../lib
    - make clean

    # Then make GSL library
    - cd ../../software/gsl-1.15
    - ./configure --disable-shared --prefix=$PYTHON/gsl
    - make
    - make check 2>&1
    - make install
    - make clean

script:
    - cd $TRAVIS_BUILD_DIR
    - make test
